name: Test
"on":
  push:
    branches:
      - master
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  npmCi:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm test
  do-examples-need-regenerating:
    name: Do examples need to be regenerated?
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run build:events -- --check --cached
      - run: git status
      - run: |
          git diff --exit-code || bash -c \
            'echo "::error file=api.github.com/index.json::This needs to be regenerated by running \`build:events -- --cached\`" && false'
