name: Test
"on":
  push:
    branches:
      - master
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  npmCi:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm test
  do-examples-need-regenerating:
    name: Do examples need to be regenerated?
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run build:events -- --check --cached
      - run: git status
      - run: |
          git diff --exit-code || bash -c \
            'echo "::error file=api.github.com/index.json::This needs to be regenerated by running \`build:events -- --cached\`" && false'
